site_name: UCE Documentation
repo_url: https://github.com/texttechnologylab/UCE
site_url: https://texttechnologylab.github.io/UCE/
docs_dir: docs
theme:
  name: material
  custom_dir: overrides
  font:
    text: Schibsted Grotesk
  #logo: /img/goethe-logo.png
  #icon:
  #  logo: fontawesome/solid/book-atlas
  favicon: img/favicon.ico
  features:
    - content.tooltips
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    #- toc.integrate
    - navigation.top
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - css/site.css

nav:
  - Home: index.md
  - UCE:
    - About: about/about.md
    - Annotations: about/annotations.md
    - Ontologies: about/ontologies.md
  - Getting Started:
    - Getting Started: getting-started/index.md
    - Web Portal: getting-started/webportal.md
    - Corpus Importer: getting-started/corpus-importer.md
    - RAG Service: getting-started/rag-service.md
    - Sparql Service: getting-started/fuseki-sparql.md
    - S3 MinIO Storage: getting-started/s3-storage.md
    - Keycloak: getting-started/keycloak.md
    - Configurations: getting-started/configuration.md
    - UIMA & DUUI: getting-started/uima-duui.md
  - Development:
    - Developer Code: development/developer-code.md
  - Projects:
    - Projects: projects/index.md
    - BIOfid: projects/biofid.md
    - PrismAI: projects/prismai.md
  - About Us:
    - About Us: about-us/about-us.md
  - Publications: publications.md

plugins:
  - search
  - git-revision-date-localized # For last modified date. ACTIVATE FOR RELEASE
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/68bFC86JRT
    - icon: fontawesome/brands/github
      link: https://github.com/texttechnologylab/UCE
    - icon: fontawesome/solid/house
      link: https://www.texttechnologylab.org/
  
#copyright: Copyright &copy; 2025 Text Technology Lab, Goethe-University Frankfurt